export const locationData = {
  en: {
    "Colombo": ["Colombo 1", "Colombo 2", "Colombo 3", "Colombo 4", "Colombo 5", "Colombo 6", "Colombo 7", "Colombo 8", "Dehiwala", "Mount Lavinia", "Moratuwa", "Kotte", "Maharagama", "Kesbewa", "Boralesgamuwa", "Piliyandala", "Nugegoda", "Homagama", "Kaduwela", "Malabe", "Kottawa", "Pannipitiya", "Battaramulla"],
    "Gampaha": ["Gampaha", "Negombo", "Katunayake", "Ja-Ela", "Wattala", "Kelaniya", "Peliyagoda", "Ragama", "Kadawatha", "Kiribathgoda", "Minuwangoda", "Veyangoda", "Divulapitiya", "Nittambuwa", "Ganemulla"],
    "Kalutara": ["Kalutara", "Panadura", "Horana", "Beruwala", "Aluthgama", "Matugama", "Wadduwa", "Bandaragama"],
    "Kandy": ["Kandy", "Peradeniya", "Gampola", "Nawalapitiya", "Katugastota", "Galagedara", "Wattegama", "Akurana", "Kadugannawa"],
    "Matale": ["Matale", "Dambulla", "Sigiriya", "Galewela", "Ukuwela", "Rattota"],
    "Nuwara Eliya": ["Nuwara Eliya", "Hatton", "Nuwara Eliya", "Talawakelle", "Ginigathena", "Walapane"],
    "Galle": ["Galle", "Hikkaduwa", "Ambalangoda", "Elpitiya", "Bentota", "Baddegama", "Karapitiya"],
    "Matara": ["Matara", "Weligama", "Mirissa", "Dikwella", "Akuressa", "Hakmana"],
    "Hambantota": ["Hambantota", "Tangalle", "Tissamaharama", "Ambalantota", "Beliatta"],
    "Jaffna": ["Jaffna", "Nallur", "Chavakachcheri", "Point Pedro", "Karainagar"],
    "Kilinochchi": ["Kilinochchi", "Pallai", "Paranthan"],
    "Mannar": ["Mannar", "Nanattan", "Madhu"],
    "Vavuniya": ["Vavuniya", "Nedunkeni", "Omanthai"],
    "Mullaitivu": ["Mullaitivu", "Oddusuddan", "Puthukudiyiruppu"],
    "Batticaloa": ["Batticaloa", "Kattankudy", "Eravur", "Kaluwanchikudy"],
    "Ampara": ["Ampara", "Kalmunai", "Akkaraipattu", "Sammanthurai", "Pottuvil"],
    "Trincomalee": ["Trincomalee", "Kinniya", "Mutur", "Kantale"],
    "Kurunegala": ["Kurunegala", "Kuliyapitiya", "Narammala", "Wariyapola", "Pannala", "Melsiripura", "Mawathagama"],
    "Puttalam": ["Puttalam", "Chilaw", "Wennappuwa", "Nattandiya", "Dankotuwa", "Marawila"],
    "Anuradhapura": ["Anuradhapura", "Kekirawa", "Medawachchiya", "Tambuttegama", "Eppawala", "Galenbindunuwewa"],
    "Polonnaruwa": ["Polonnaruwa", "Kaduruwela", "Medirigiriya", "Hingurakgoda"],
    "Badulla": ["Badulla", "Bandarawela", "Haputale", "Welimada", "Mahiyanganaya", "Passara"],
    "Monaragala": ["Monaragala", "Wellawaya", "Bibile", "Buttala"],
    "Ratnapura": ["Ratnapura", "Embilipitiya", "Balangoda", "Pelmadulla", "Eheliyagoda", "Kuruwita"],
    "Kegalle": ["Kegalle", "Mawanella", "Warakapola", "Rambukkana", "Galigamuwa", "Dehiowita"]
  },
  si: {
    "කොලම": ["කොළඹ 1", "කොළඹ 2", "කොළඹ 3", "කොළඹ 4", "කොළඹ 5", "කොළඹ 6", "කොළඹ 7", "කොළඹ 8", "දෙහිවල", "ගල්කිස්ස", "මොරටුව", "කෝට්ටේ", "මහරගම", "කැස්බෑව", "බොරලැස්ගමුව", "පිලියන්දල", "නුගේගොඩ", "හෝමාගම", "කඩුවෙල", "මාලබේ", "කොට්ටාව", "පන්නිපිටිය", "බත්තරමුල්ල"],
    "ගම්පහ": ["ගම්පහ", "මීගමුව", "කටුනායක", "ජා-ඇල", "වත්තල", "කැලණිය", "පෑලියගොඩ", "රාගම", "කඩවත", "කිරිබත්ගොඩ", "මිනුවන්ගොඩ", "වේයන්ගොඩ", "දිවුලපිටිය", "නිට්ටඹුව", "ගනේමුල්ල"],
    "කලුතර": ["කළුතර", "පානදුර", "හෝරණ", "බේරුවල", "අලුත්ගම", "මාතුගම", "වාද්දූව", "බණ්ඩාරගම"],
    "මහනුවර": ["මහනුවර", "පේරාදෙණිය", "ගම්පොළ", "නාවලපිටිය", "කටුගස්තොට", "ගලගෙදර", "වත්තේගම", "අකුරණ", "කඩුගන්නාව"],
    "මතලේ": ["මාතලේ", "දඹුල්ල", "සීගිරිය", "ගලේවෙල", "උකුවෙල", "රත්තොට"],
    "නුවරේලිය": ["නුවරඑළිය", "හැටන්", "නුවරඑළිය", "තලවාකැලේ", "ගිනිගතැන", "වලපනේ"],
    "ගාල්ල": ["ගාල්ල", "හික්කඩුව", "අම්බලන්ගොඩ", "එල්පිටිය", "බෙන්තොට", "බද්දේගම", "කරපිටිය"],
    "මාතර": ["මාතර", "වැලිගම", "මිරිස්ස", "දික්වැල්ල", "අකුරැස්ස", "හක්මන"],
    "හම්බන්තොට": ["හම්බන්තොට", "තංගල්ල", "තිස්සමහාරාම", "අම්බලන්තොට", "බෙලිඅත්ත"],
    "යාපනය": ["යාපනය", "නල්ලූර්", "චාවකච්චේරි", "පොයින්ට් පේද්‍රු", "කරයිනගර්"],
    "කිලිනෝච්චි": ["කිලිනොච්චි", "පල්ලෙයි", "පරන්තන්"],
    "මන්නාරම": ["මන්නාරම", "නානත්තන්", "මඩු"],
    "වවුනියාව": ["වවුනියාව", "නෙදුන්කෙණි", "ඔමන්තායි"],
    "මුල්ලැතීවු": ["මුල්ලෙයිතිව්", "ඔඩ්ඩුසුඩ්ඩාන්", "පුතුකුඩියිරුප්පු"],
    "මටකලපුව": ["මඩකලපුව", "කාත්තන්කුඩි", "ඒරාවුර්", "කලුවන්චිකුඩි"],
    "අම්පාර": ["අම්පාර", "කල්මුණේ", "අක්කරපත්තු", "සම්මන්තුරේ", "පොතුවිල්"],
    "ත්රිකුණාමලය": ["ත්රිකුණාමලය", "කින්නියා", "මුතුර්", "කන්තලේ"],
    "කුරුණැගල": ["කුරුණෑගල", "කුලියාපිටිය", "නාරම්මල", "වාරියපොල", "පන්නල", "මැල්සිරිපුර", "මාවතගම"],
    "පුත්තලම": ["පුත්තලම", "චිලාව", "වෙන්නප්පුව", "නත්තන්ඩිය", "දංකොටුව", "මාරවිල"],
    "අනුරාධපුරය": ["අනුරාධපුරය", "කැකිරාව", "මැදවච්චිය", "තඹුත්තේගම", "එප්පාවල", "ගලෙන්බිඳුනුවැව"],
    "පොලොන්නරුව": ["පොළොන්නරුව", "කදුරුවෙල", "මැදිරිගිරිය", "හිඟුරක්ගොඩ"],
    "බදුල්ල": ["බදුල්ල", "බණ්ඩාරවෙල", "හපුතලේ", "වැලිමඩ", "මහියංගනය", "පස්සර"],
    "මොණරාගල": ["මොණරාගල", "වැල්ලවාය", "බිබිලේ", "බුත්තල"],
    "රත්නපුර": ["රත්නපුර", "එඹිලිපිටිය", "බලංගොඩ", "පැල්මඩුල්ල", "ඇහැලියගොඩ", "කුරුවිට"],
    "කැගල්ල": ["කෑගල්ල", "මාවනැල්ල", "වරකාපොල", "රඹුක්කන", "ගලිගමුව", "දෙහිඕවිට"]
  }
};

export const getDistricts = (language) => Object.keys(locationData[language]);
export const getCities = (language, district) => locationData[language][district] || [];
