export const locationData = {
  "Colombo": ["Colombo 1", "Colombo 2", "Colombo 3", "Colombo 4", "Colombo 5", "Colombo 6", "Colombo 7", "Colombo 8", "Dehiwala", "Mount Lavinia", "Moratuwa", "Kotte", "Maharagama", "Kesbewa", "Boralesgamuwa", "Piliyandala", "Nugegoda", "Homagama", "Kaduwela", "Malabe", "Kottawa", "Pannipitiya", "Battaramulla"],
  "Gampaha": ["Gampaha", "Negombo", "Katunayake", "Ja-Ela", "Wattala", "Kelaniya", "Peliyagoda", "Ragama", "Kadawatha", "Kiribathgoda", "Minuwangoda", "Veyangoda", "Divulapitiya", "Nittambuwa", "Ganemulla"],
  "Kalutara": ["Kalutara", "Panadura", "Horana", "Beruwala", "Aluthgama", "Matugama", "Wadduwa", "Bandaragama"],
  "Kandy": ["Kandy", "Peradeniya", "Gampola", "Nawalapitiya", "Katugastota", "Galagedara", "Wattegama", "Akurana", "Kadugannawa"],
  "Matale": ["Matale", "Dambulla", "Sigiriya", "Galewela", "Ukuwela", "Rattota"],
  "Nuwara Eliya": ["Nuwara Eliya", "Hatton", "Nuwara Eliya", "Talawakelle", "Ginigathena", "Walapane"],
  "Galle": ["Galle", "Hikkaduwa", "Ambalangoda", "Elpitiya", "Bentota", "Baddegama", "Karapitiya"],
  "Matara": ["Matara", "Weligama", "Mirissa", "Dikwella", "Akuressa", "Hakmana"],
  "Hambantota": ["Hambantota", "Tangalle", "Tissamaharama", "Ambalantota", "Beliatta"],
  "Jaffna": ["Jaffna", "Nallur", "Chavakachcheri", "Point Pedro", "Karainagar"],
  "Kilinochchi": ["Kilinochchi", "Pallai", "Paranthan"],
  "Mannar": ["Mannar", "Nanattan", "Madhu"],
  "Vavuniya": ["Vavuniya", "Nedunkeni", "Omanthai"],
  "Mullaitivu": ["Mullaitivu", "Oddusuddan", "Puthukudiyiruppu"],
  "Batticaloa": ["Batticaloa", "Kattankudy", "Eravur", "Kaluwanchikudy"],
  "Ampara": ["Ampara", "Kalmunai", "Akkaraipattu", "Sammanthurai", "Pottuvil"],
  "Trincomalee": ["Trincomalee", "Kinniya", "Mutur", "Kantale"],
  "Kurunegala": ["Kurunegala", "Kuliyapitiya", "Narammala", "Wariyapola", "Pannala", "Melsiripura", "Mawathagama"],
  "Puttalam": ["Puttalam", "Chilaw", "Wennappuwa", "Nattandiya", "Dankotuwa", "Marawila"],
  "Anuradhapura": ["Anuradhapura", "Kekirawa", "Medawachchiya", "Tambuttegama", "Eppawala", "Galenbindunuwewa"],
  "Polonnaruwa": ["Polonnaruwa", "Kaduruwela", "Medirigiriya", "Hingurakgoda"],
  "Badulla": ["Badulla", "Bandarawela", "Haputale", "Welimada", "Mahiyanganaya", "Passara"],
  "Monaragala": ["Monaragala", "Wellawaya", "Bibile", "Buttala"],
  "Ratnapura": ["Ratnapura", "Embilipitiya", "Balangoda", "Pelmadulla", "Eheliyagoda", "Kuruwita"],
  "Kegalle": ["Kegalle", "Mawanella", "Warakapola", "Rambukkana", "Galigamuwa", "Dehiowita"]
};
